# Generated by Django 5.2.11 on 2026-04-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('acronym', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parties/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('head_candidate', models.CharField(max_length=150)),
                ('total_seats', models.PositiveIntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commune')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.politicalparty')),
            ],
        ),
    ]
