# Generated by Django 5.2.11 on 2026-04-13 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electorallist',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='physicalresult',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AlterField(
            model_name='electorallist',
            name='voter_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='electorallist',
            unique_together={('voter_id', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='physicalresult',
            unique_together={('station', 'party', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('electoral', 'election')},
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.pollingstation')),
            ],
        ),
    ]
