# Generated by Django 5.2.11 on 2026-04-05 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electorallist',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='electorallist',
            name='head_candidate',
        ),
        migrations.RemoveField(
            model_name='electorallist',
            name='party',
        ),
        migrations.RemoveField(
            model_name='electorallist',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='electorallist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='lists/images/'),
        ),
        migrations.AddField(
            model_name='electorallist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electorallist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electorallist',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='lists/images/'),
        ),
        migrations.AddField(
            model_name='electorallist',
            name='party_acronym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electorallist',
            name='program_document',
            field=models.FileField(blank=True, null=True, upload_to='lists/docs/'),
        ),
        migrations.AlterField(
            model_name='electorallist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
