# Generated by Django 5.2.11 on 2026-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_center_election_election_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalresult',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
