# Generated by Django 5.2.11 on 2026-04-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_votingcenter_pollingstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_voters', models.IntegerField(default=0)),
                ('blank_votes', models.IntegerField(default=0)),
                ('valid_votes', models.IntegerField(default=0)),
                ('polling_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_voters', models.IntegerField()),
                ('blank_votes', models.IntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='VoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('electoral_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electorallist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='elections.votesession')),
            ],
        ),
    ]
