# Generated by Django 5.2.11 on 2026-04-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_electionconfig_electionstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electorallist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electorallist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electoral_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='electorallist',
            constraint=models.UniqueConstraint(fields=('voter_id', 'election'), name='unique_voter_per_election'),
        ),
    ]
