# Generated by Django 5.2.11 on 2026-04-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('elections', '0003_physicalresult_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.center'),
        ),
    ]
